Add a livenessProbe to Concourse workers that detects fatal errors.
Logs seem to be the only reliable way of detecting issues that prevent workers from taking on work. Tee the log to a file, and truncate it each time the livenessProbe runs.

Fixes https://github.com/kubernetes/charts/issues/2104

diff --git a/stable/concourse/templates/worker-statefulset.yaml b/stable/concourse/templates/worker-statefulset.yaml
--- a/stable/concourse/templates/worker-statefulset.yaml
+++ b/stable/concourse/templates/worker-statefulset.yaml
@@ -44,8 +44,25 @@ spec:
           args:
             - -c
             - |-
-              concourse worker --name=${HOSTNAME}
+              cp /dev/null /concourse-work-dir/.liveness_probe
+              concourse worker --name=${HOSTNAME} | tee -a /concourse-work-dir/.liveness_probe
               sleep ${POST_STOP_DELAY_SECONDS}
+          livenessProbe:
+            exec:
+              command:
+                - /bin/sh
+                - -c
+                - |-
+                  FATAL_ERRORS=$([ ! -z "${LIVENESS_PROBE_FATAL_ERRORS// }" ] && \
+                      grep -F "${LIVENESS_PROBE_FATAL_ERRORS}" /concourse-work-dir/.liveness_probe)
+                  cp /dev/null /concourse-work-dir/.liveness_probe
+                  if [ ! -z "${FATAL_ERRORS}" ]; then
+                    >&2 echo "Fatal error detected: ${FATAL_ERRORS}"
+                    exit 1
+                  fi
+            failureThreshold: 1
+            initialDelaySeconds: 10
+            periodSeconds: 10
           lifecycle:
             preStop:
               exec:
@@ -90,6 +107,11 @@ spec:
                 configMapKeyRef:
                   name: {{ template "concourse.fullname" . }}
                   key: worker-post-stop-delay-seconds
+            - name: LIVENESS_PROBE_FATAL_ERRORS
+              valueFrom:
+                configMapKeyRef:
+                  name: {{ template "concourse.fullname" . }}
+                  key: worker-fatal-errors
           resources:
 {{ toYaml .Values.worker.resources | indent 12 }}
           securityContext:
